name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: go.sum
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Run tests with race detector & coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi
    
    - name: Generate HTML coverage report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage HTML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: coverage.html
        retention-days: 30
